### ISSUE TITLE
Suggestions for project topic

### ISSUE THREAD

**Issue by rrrohit1** [UBC-MDS/netflixpy_dashboard#1]

**Comment by Anahita97** [comment]
Here are some topic ideas: [Netflix data set](https://www.kaggle.com/shivamb/netflix-shows), the [World Development Indicator](https://databank.worldbank.org/source/education-statistics-%5E-all-indicators) data set by World Bank, daily updated [Covid](https://github.com/CSSEGISandData/COVID-19/tree/master/csse_covid_19_data) dataset, the [happiness](https://www.kaggle.com/javadzabihi/happiness-2017-visualization-prediction/data) dataset and the [US police shooting](https://www.kaggle.com/ahsen1330/us-police-shootings) dataset.
