### ISSUE TITLE
Plot for directors

### ISSUE THREAD

**Issue by jo4356** [UBC-MDS/netflixpy_dashboard#24]

**Comment by rrrohit1** [comment]
Currently looks like this.

<img width="786" alt="image" src="https://user-images.githubusercontent.com/52863845/156452811-e2959b9c-1c38-466d-9e3d-b92595682252.png">

**Comment by rrrohit1** [comment]
Link for my branch update: @jo4356 

https://github.com/UBC-MDS/netflixpy_dashboard/blob/app-rohit/src/app.py
