### ISSUE TITLE
App sketch & description

### ISSUE THREAD

**Issue by rrrohit1** [UBC-MDS/netflixpy_dashboard#7]
- [x] Make dashboard sketch
- [x] Description 200-300 words in `README.md`

**Comment by jo4356** [comment]
Brainstorming

selection
- selecting movie/TV show
- select by country
- select by release year
- select by type (listed_in column)
- select by rating

plots
- plot number of movies/shows by release year (line plot)
- plot number of movies/shows by country (bar plot)
- plot number of movies/shows by type (bar plot)
- plot show/movie duration?
- select by year and plot multiple categories of movies/shows  (country, type, rating, etc)

others
- allow showing individual movie name and descriptions?
